# Users schema

# --- !Ups

ALTER TABLE "STEAM_DATA"
DROP COLUMN "STEAM_DATA_WISH_LIST";

ALTER TABLE "GOG_DATA"
DROP COLUMN "GOG_DATA_WISH_LIST";

# --- !Downs
ALTER TABLE "STEAM_DATA"
ADD "STEAM_DATA_WISH_LIST" BOOLEAN;

ALTER TABLE "GOG_DATA"
ADD "GOG_DATA_WISH_LIST" BOOLEAN;
