# Users schema

# --- !Ups

ALTER TABLE "STEAM_DATA"
ADD "STEAM_DATA_PRICE_DISCOUNTED" REAL;

ALTER TABLE "GOG_DATA"
ADD "GOG_DATA_PRICE_DISCOUNTED" REAL;

# --- !Downs
ALTER TABLE "STEAM_DATA"
DROP COLUMN "STEAM_DATA_PRICE_DISCOUNTED";

ALTER TABLE "GOG_DATA"
DROP COLUMN "GOG_DATA_PRICE_DISCOUNTED";